apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cast-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: cast_db_dev
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  name: postgres-cast 
                  key: POSTGRES_PASSWORD 
            - name: POSTGRES_USER
              valueFrom: 
                secretKeyRef: 
                  name: postgres-cast 
                  key: POSTGRES_USER
          image: postgres:12.1-alpine
          name: cast-db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-cast-pvc
