apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cast_db.service.name }}
spec:
  ports:
    - port: {{ .Values.cast_db.service.port }}
      targetPort: {{ .Values.cast_db.service.targetPort }}
  selector:
    app: {{ .Values.cast_db.metadata.label }}
