apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:latest
          name: nginx
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: nginx-conf
              subPath: default.conf
      volumes:
        - name: nginx-conf
          configMap:
            items:
              - key: nginx_config.conf
                path: default.conf
            name: nginx-configmap
      #volumes:
      #  - name: nginx-conf
       #   persistentVolumeClaim:
        #    claimName: nginx-pvc
