apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.movie_service.service.name }}
spec:
 type: {{ .Values.movie_service.service.type }}
 ports:
   - name: "http"
     port: {{ .Values.movie_service.service.port }}
     targetPort: {{ .Values.movie_service.service.targetPort }}
 selector:
   app: {{ .Values.movie_service.metadata.label }}
