apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-configmap
data:
  cast_host_url: http://cast-service:8002/api/v1/casts/
  DATABASE_URI: postgresql://movie_db_username:movie_db_password@movie-db/movie_db_dev
