apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.movie_db.service.name }}
spec:
  ports:
    - name: "http"
      port: {{ .Values.movie_db.service.port }}
      targetPort: {{ .Values.movie_db.service.targetPort }}
  selector:
    app: {{ .Values.movie_db.metadata.label }}
