apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie_service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie_service
  template:
    metadata:
      labels:
        app: movie_service
    spec:
      containers:
        - name: movie_service
          image: jenkins_devops_exams_movie_service
          imagePullPolicy: IfNotPresent
          command: ["bash", "-c"]
          args: ["uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"]
          env:
            - name: CAST_SERVICE_HOST_URL
              valueFrom:
                configMapKeyRef:
                  name: movie-configmap
                  key: CAST_SERVICE_HOST_URL             
            - name: DATABASE_URI
              valueFrom:
                configMapKeyRef:
                  name: movie-configmap
                  key: DATABASE_URI
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /home/movie_data
              name: movie-data
      volumes:
        - name: movie-data
          persistentVolumeClaim:
            claimName: movie-pvc
